#pragma once

IWTOUE_API DECLARE_LOG_CATEGORY_EXTERN(LogCast, Log, All);
IWTOUE_API DECLARE_LOG_CATEGORY_EXTERN(LogITUDatabase, Log, All);
IWTOUE_API DECLARE_LOG_CATEGORY_EXTERN(LogITUAssetImporter, Log, All);
IWTOUE_API DECLARE_LOG_CATEGORY_EXTERN(LogITUMemoryReader, Log, All);